version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.3
    ports:
      - 5672:5672
    hostname: rabbitmq
  orchestrator:
    build: orchestrator
    ports:
      - 8080:8080
    environment:
      AMQP_URI: 'amqp://guest:guest@rabbitmq:5672/'
      HTTP_URI: '0.0.0.0:8080'
    links:
      - rabbitmq
  body_part:
    build: body_part
    environment:
      AMQP_URI: 'rabbitmq'
    links:
      - rabbitmq
